# PostgreSQL. Versions 9.3 and up are supported.
#
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: db
  port: 5432
  username: <%= ENV.fetch("DATABASE_USERNAME") { "" } %>
  password: <%= ENV.fetch("DATABASE_PASSWORD") { "" } %>

development:
  <<: *default
  database: space_travel_development

test:
  <<: *default
  database: space_travel_test

production:
  <<: *default
  database: space_travel_production
  username: space_travel
  password: <%= ENV["SPACE_TRAVEL_DATABASE_PASSWORD"] %>
